---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
implicit:
  - Конвертация цен в рубли при выборе русского языка
  - Возможность изменять активное фото при переходе в карточку товара
  - При выборе русского языка описания товаров и названия категорий товаров должны переводиться на русский язык
  - При выборе категории должны оставаться только те производители, которые имеют в своем перечне товар из выбранно категории
  - Должна быть возможность выбрать несколько категорий товара и вернуться к товарам без привязки  к категории
